//@version=4
study("Improved Scalping Indicator", overlay=true) 

// Inputs
fastLength = input(20, title="Fast MA") // 20 this worked good
slowLength = input(40, title="Slow MA") // 40 

//rsiLength = input(50, title="RSI Length")

// Additional filters
priceOver200SMA = close > sma(close, 200)
priceUnder200SMA = close < sma(close, 200)
//macdhistogram = macd(close, 12, 26)

// Trading conditions
//longCondition = crossover(sma(close, fastLength), sma(close, slowLength)) and rsi(close, rsiLength) < 30 and priceOver200SMA
//shortCondition = crossunder(sma(close, fastLength), sma(close, slowLength)) and rsi(close, rsiLength) > 70 and priceUnder200SMA
longCondition = crossover(sma(close, fastLength), sma(close, slowLength)) and priceOver200SMA
shortCondition = crossunder(sma(close, fastLength), sma(close, slowLength)) and priceUnder200SMA
//longCondition = crossover(sma(close, fastLength), sma(close, slowLength)) and rsi(close, rsiLength) < 30 
//shortCondition = crossunder(sma(close, fastLength), sma(close, slowLength)) and rsi(close, rsiLength) > 70

// Long/short logic
long = false
short = false
if (longCondition)
    long := true  
if (shortCondition)
    long := false
    
if (shortCondition)
    short := true
if (longCondition)   
    short := false
       
// Plotting
plot(sma(close, fastLength), color=#2962FF)
plot(sma(close, slowLength), color=#FF6347)

// Buy signal
plotshape(longCondition, style=shape.triangleup, location=location.belowbar, color=color.green, size=size.small)
// Sell signal
plotshape(shortCondition, style=shape.triangledown, location=location.abovebar, color=color.red, size=size.small)

bgcolor(long ? color.green : na)
bgcolor(short ? color.red : na)

alertcondition(longCondition, title="Long Signal", message="Go Long")
alertcondition(shortCondition, title="Short Signal", message="Go Short")
